name: flutter_counter
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  bloc: ^8.1.2
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3

dev_dependencies:
  bloc_test: ^9.1.5
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  integration_test:
    sdk: flutter
  mocktail: ^1.0.0

flutter:
  uses-material-design: true
